### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Chawangmushi** [Chawangmushi/protospace-36080#1]
https://protospace-36080.herokuapp.com/

ターミナルにheroku apps:infoコマンドを入力することで確認可能。
提出前項目を自分では全ての項目を確認を行い問題ないことを確認した。

**Comment by snkw-works** [comment]
@Chawangmushi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
ユーザー名が正しく表示されていない状態です。
<img width="1194" alt="スクリーンショット 2021-07-12 17 36 55" src="https://user-images.githubusercontent.com/54050089/125256917-db7c6080-e337-11eb-8ab5-5a2c0f5f056e.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Chawangmushi** [comment]
> @Chawangmushi さん、ご提出ありがとうございます‼︎
> 動作の確認をしたところ、修正していただきたい箇所がございました。
> 以下、ご確認をお願いします！
> 
> [修正依頼箇所]
> 
> * [ ]  **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
>   ユーザー名が正しく表示されていない状態です。
> 
> <img alt="スクリーンショット 2021-07-12 17 36 55" width="1194" src="https://user-images.githubusercontent.com/54050089/125256917-db7c6080-e337-11eb-8ab5-5a2c0f5f056e.png">
> 
> 修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
> ※新しいissueを作っていただく必要はございません。
> https://forms.gle/ZdLeprTTWhMA8aZA7

「ユーザー名」さんの情報
「ユーザー名」さんのプロトタイプの部分でしょうか？

失礼しました。この部分は忘れておりました。すぐに修正したいと思います。

**Comment by takumi0530** [comment]
@Chawangmushi さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by Chawangmushi** [comment]
> @Chawangmushi さん、再度ご提出ありがとうございます‼︎
> 問題なく正常に動作することが確認できました！　LGTMです✨　
> おめでとうございます🎉
> 
> 次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
> 別途、最終課題の案内をチャンネルに送らせて頂きます。
> 今しばらくお待ちください🍀

レビューありがとうございます。
自分で考え、自力で調べて
やっとできたアプリでLGTMをいただけたので嬉しいです。
